import {
  Loader2,
  Brain,
  LayoutDashboard,
  CheckSquare,
  Calendar,
  Timer,
  BarChart3,
  Sparkles,
  User,
  Settings,
  Bell,
  Search,
  Plus,
  Play,
  Pause,
  RotateCcw,
  ChevronRight,
  Clock,
  Target,
  TrendingUp,
  Zap,
  Trash2,
  LogOut,
  Briefcase,
  Book,
  Heart,
  Circle,
  Leaf,
  Sprout,
  TreePine,
  Flower,
  Sun,
  Droplets,
  SproutIcon as Seedling,
  Music,
  Volume2,
  Square,
  Check,
  Stars,
  X,
  Maximize2,
  Minimize2,
  Layout,
  Type,
  AlignLeft,
  Tag,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  brain: Brain,
  dashboard: LayoutDashboard,
  tasks: CheckSquare,
  calendar: Calendar,
  timer: Timer,
  insights: BarChart3,
  sparkles: Sparkles,
  user: User,
  settings: Settings,
  bell: Bell,
  search: Search,
  plus: Plus,
  play: Play,
  pause: Pause,
  reset: RotateCcw,
  chevronRight: ChevronRight,
  clock: Clock,
  target: Target,
  trendingUp: TrendingUp,
  zap: Zap,
  trash: Trash2,
  logout: LogOut,
  briefcase: Briefcase,
  book: Book,
  heart: Heart,
  circle: Circle,
  // Nature/Plant themed icons
  leaf: Leaf,
  sprout: Sprout,
  tree: TreePine,
  flower: Flower,
  sun: Sun,
  droplets: Droplets,
  seedling: Seedling,
  // Music icons
  music: Music,
  volume: Volume2,
  stop: Square,
  check: Check,
  stars: Stars,
  // UI icons
  close: X,
  maximize: Maximize2,
  minimize: Minimize2,
  layout: Layout,
  type: Type,
  alignLeft: AlignLeft,
  tag: Tag,
}
