import {
  FiLoader,
  FiGrid,
  FiCheckSquare,
  FiCalendar,
  FiClock,
  FiBarChart2,
  FiStar,
  FiUser,
  FiSettings,
  FiBell,
  FiSearch,
  FiPlus,
  FiPlay,
  FiPause,
  FiRotateCcw,
  FiChevronRight,
  FiTarget,
  FiTrendingUp,
  FiZap,
  FiTrash2,
  FiLogOut,
  FiBriefcase,
  FiBook,
  FiHeart,
  FiCircle,
  FiSun,
  FiDroplet,
  FiMusic,
  FiVolume2,
  FiSquare,
  FiCheck,
  FiX,
  FiMaximize2,
  FiMinimize2,
  FiLayout,
  FiType,
  FiAlignLeft,
  FiTag,
  FiCloudRain,
} from "react-icons/fi"

import {
  FaBrain,
  FaLeaf,
  FaSeedling,
  FaTree,
} from "react-icons/fa"

import { MdLocalFlorist } from "react-icons/md"

export const Icons = {
  spinner: FiLoader,
  brain: FaBrain,
  dashboard: FiGrid,
  tasks: FiCheckSquare,
  calendar: FiCalendar,
  timer: FiClock,
  insights: FiBarChart2,
  sparkles: FiStar,
  user: FiUser,
  settings: FiSettings,
  bell: FiBell,
  search: FiSearch,
  plus: FiPlus,
  play: FiPlay,
  pause: FiPause,
  reset: FiRotateCcw,
  chevronRight: FiChevronRight,
  clock: FiClock,
  target: FiTarget,
  trendingUp: FiTrendingUp,
  zap: FiZap,
  trash: FiTrash2,
  logout: FiLogOut,
  briefcase: FiBriefcase,
  book: FiBook,
  heart: FiHeart,
  circle: FiCircle,
  // Nature/Plant themed icons
  leaf: FaLeaf,
  sprout: FaSeedling,
  tree: FaTree,
  flower: MdLocalFlorist,
  sun: FiSun,
  droplets: FiDroplet,
  seedling: FaSeedling,
  // Music icons
  music: FiMusic,
  volume: FiVolume2,
  stop: FiSquare,
  check: FiCheck,
  stars: FiStar,
  // UI icons
  close: FiX,
  maximize: FiMaximize2,
  minimize: FiMinimize2,
  layout: FiLayout,
  type: FiType,
  alignLeft: FiAlignLeft,
  tag: FiTag,
  cloudRain: FiCloudRain,
}
